### PR TITLE
Fix tspawnat on julia 1.7+ by making the task sticky

### LINKED ISSUE #32: Tasks spawned with tspawnat can migrate on 1.7
Using ThreadPools v2.1.0 and Julia v1.7.1, tasks spawned with `@tspawnat` can migrate between threads. Tasks spawned this way always spawn on the correct thread as given to the macro, but can migrate to another thread during execution.

There is some existing work to add support for sticky tasks in 1.7+ in this PR https://github.com/JuliaLang/julia/pull/42302 but it will not land for some time.

Are you interested in supporting sticky tasks in 1.7+ in this package? From my testing, it would be a simple change. Just allow the user to set `sticky` to `true` here: https://github.com/tro3/ThreadPools.jl/blob/master/src/macros.jl#L270

cc @IanButterworth

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes #32 

I wasn't sure of the implication of setting `sticky = true` on < v1.7, so I played safe and left that as-is

cc. @Octogonapus @carstenbauer

### CODE REVIEW

**Comment by IanButterworth** [comment]
@tro3 I also noticed that there's no CI set up so I added github actions.

Would you mind approving the CI run, or better yet, changing the (annoying) github default to run CI for non-new github users

(I'd also be happy to help as a collaborator on the repo)

**Comment by tro3** [comment]
@IanButterworth - will do to both.  I find myself out of the Julia domain nowadays, but I will be keeping up to date.  But help is always appreciated. :-)

**Comment by IanButterworth** [comment]
Ok. Seems like CI is set up now. I can merge and release if you like @tro3. As you prefer

**Comment by tro3** [comment]
@IanButterworth go for it.  Thanks!

**Pull request merged**
