### PR TITLE
Interpolation syntax with @tspawnat

### PR DESCRIPTION
**Pull request by wsphillips**
This ought to do it. Fix for #16

### CODE REVIEW

**Comment by tro3** [comment]
This looks good.  Do you have a testcase you could add to /tests that demonstrates fail before / pass after?  If not, I can generate one, and check Julia version compatibility.

**Comment by wsphillips** [comment]
I don't have a test handy, but the original implementation will fail outright if you try to pass in an interpolated variable. To prove it works, it would be something like:
```julia
function foo(x)
    sleep(0.01)
    return x
end

# With interpolation
x = 1
expect_sum = 3
t1 = @tspawnat 2 foo($x)
x += 1
t2 = @tspawnat 3 foo($x)

test_sum = fetch(t1) + fetch(t2)
@test expect_sum == test_sum

# without interpolation
x = 1
t1 = @tspawnat 2 foo(x)
x += 1
t2 = @tspawnat 3 foo(x)
test_sum = fetch(t1) + fetch(t2)
@test expect_sum == test_sum # should fail; sum will be 4
```

**Comment by tro3** [comment]
Okay, I have an implementation using the VERSION check, but the above test case does not properly fail without interpolation.  Do you have a use case that required it?  I'll try to come up with one as well.

**Comment by tro3** [comment]
Well, I guess it doesn't matter.  Interpolation works with it in place, and dies without it.

**Comment by tro3** [comment]
Okay, interpolation upgrade with test for 1.4 (but tests passing at 1.3) are in place.  Revving version the Registrator now.  Thanks for the help!

**Pull request closed without merging**
